// File: src/data/mockData.js
// This file contains mock data for Indian consumer personas

export const MOCK_PERSONA_DATA = [
  {
    "Persona ID": "P-001",
    "Type": "High-Income Executive",
    "Age": 60,
    "Location": "Jaipur",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Instagram",
    "Core Value": "Sustainability",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.67,
    "Digital Influence Score": 0.55,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-002",
    "Type": "Young Professional",
    "Age": 46,
    "Location": "Chennai",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Twitter",
    "Core Value": "Convenience",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.85,
    "Digital Influence Score": 0.93,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-003",
    "Type": "High-Income Executive",
    "Age": 30,
    "Location": "Mumbai",
    "Income Level": "High",
    "Preferred Platform": "Reddit",
    "Core Value": "Luxury",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.41,
    "Digital Influence Score": 0.99,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  },
  {
    "Persona ID": "P-004",
    "Type": "Young Professional",
    "Age": 26,
    "Location": "Ahmedabad",
    "Income Level": "Middle",
    "Preferred Platform": "Reddit",
    "Core Value": "Sustainability",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.66,
    "Digital Influence Score": 0.11,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-005",
    "Type": "Blue-Collar Worker",
    "Age": 50,
    "Location": "Ahmedabad",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Facebook",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.59,
    "Digital Influence Score": 0.3,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-006",
    "Type": "High-Income Executive",
    "Age": 44,
    "Location": "Hyderabad",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Telegram",
    "Core Value": "Sustainability",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.18,
    "Digital Influence Score": 0.73,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I prefer word-of-mouth recommendations before buying."
  },
  {
    "Persona ID": "P-007",
    "Type": "Middle-Class Parent",
    "Age": 19,
    "Location": "Chennai",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Telegram",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.58,
    "Digital Influence Score": 0.44,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-008",
    "Type": "High-Income Executive",
    "Age": 40,
    "Location": "Jaipur",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.89,
    "Digital Influence Score": 0.9,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-009",
    "Type": "Middle-Class Parent",
    "Age": 59,
    "Location": "Ahmedabad",
    "Income Level": "High",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.44,
    "Digital Influence Score": 0.95,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "Sustainability matters to me when making a purchase."
  },
  {
    "Persona ID": "P-010",
    "Type": "Social Media Influencer",
    "Age": 57,
    "Location": "Pune",
    "Income Level": "High",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.99,
    "Digital Influence Score": 0.6,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-011",
    "Type": "Middle-Class Parent",
    "Age": 24,
    "Location": "Mumbai",
    "Income Level": "Middle",
    "Preferred Platform": "Twitter",
    "Core Value": "Traditional Values",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 1.0,
    "Digital Influence Score": 0.72,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-012",
    "Type": "Middle-Class Parent",
    "Age": 18,
    "Location": "Delhi",
    "Income Level": "Lower",
    "Preferred Platform": "Reddit",
    "Core Value": "Traditional Values",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.45,
    "Digital Influence Score": 0.84,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "Brand loyalty plays a big role in my choices."
  },
  {
    "Persona ID": "P-013",
    "Type": "Middle-Class Parent",
    "Age": 27,
    "Location": "Mumbai",
    "Income Level": "Middle",
    "Preferred Platform": "YouTube",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.22,
    "Digital Influence Score": 0.47,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I prefer word-of-mouth recommendations before buying."
  },
  {
    "Persona ID": "P-014",
    "Type": "College Student",
    "Age": 30,
    "Location": "Lucknow",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Traditional Values",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.82,
    "Digital Influence Score": 0.69,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Sustainability matters to me when making a purchase."
  },
  {
    "Persona ID": "P-015",
    "Type": "Retired Individual",
    "Age": 55,
    "Location": "Chennai",
    "Income Level": "Middle",
    "Preferred Platform": "Twitter",
    "Core Value": "Sustainability",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.88,
    "Digital Influence Score": 0.75,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-016",
    "Type": "Blue-Collar Worker",
    "Age": 19,
    "Location": "Kolkata",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Luxury",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.61,
    "Digital Influence Score": 0.49,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-017",
    "Type": "Social Media Influencer",
    "Age": 48,
    "Location": "Bangalore",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Twitter",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.42,
    "Digital Influence Score": 0.18,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-018",
    "Type": "Social Media Influencer",
    "Age": 25,
    "Location": "Jaipur",
    "Income Level": "Middle",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Luxury",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.93,
    "Digital Influence Score": 0.76,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  },
  {
    "Persona ID": "P-019",
    "Type": "High-Income Executive",
    "Age": 21,
    "Location": "Ahmedabad",
    "Income Level": "Lower",
    "Preferred Platform": "Facebook",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.97,
    "Digital Influence Score": 0.32,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-020",
    "Type": "High-Income Executive",
    "Age": 41,
    "Location": "Mumbai",
    "Income Level": "High",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Traditional Values",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Fashion",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.11,
    "Digital Influence Score": 0.44,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-021",
    "Type": "College Student",
    "Age": 43,
    "Location": "Pune",
    "Income Level": "Lower",
    "Preferred Platform": "Telegram",
    "Core Value": "Traditional Values",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.42,
    "Digital Influence Score": 0.93,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  },
  {
    "Persona ID": "P-022",
    "Type": "Freelancer",
    "Age": 51,
    "Location": "Delhi",
    "Income Level": "High",
    "Preferred Platform": "Facebook",
    "Core Value": "Luxury",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Fashion",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.9,
    "Digital Influence Score": 0.36,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  },
  {
    "Persona ID": "P-023",
    "Type": "High-Income Executive",
    "Age": 60,
    "Location": "Kolkata",
    "Income Level": "Middle",
    "Preferred Platform": "Twitter",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.85,
    "Digital Influence Score": 0.56,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  },
  {
    "Persona ID": "P-024",
    "Type": "Social Media Influencer",
    "Age": 52,
    "Location": "Bangalore",
    "Income Level": "Lower",
    "Preferred Platform": "Instagram",
    "Core Value": "Sustainability",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.93,
    "Digital Influence Score": 0.44,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-025",
    "Type": "Middle-Class Parent",
    "Age": 39,
    "Location": "Delhi",
    "Income Level": "Middle",
    "Preferred Platform": "Reddit",
    "Core Value": "Traditional Values",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.79,
    "Digital Influence Score": 0.32,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I prefer word-of-mouth recommendations before buying."
  },
  {
    "Persona ID": "P-026",
    "Type": "High-Income Executive",
    "Age": 58,
    "Location": "Delhi",
    "Income Level": "Middle",
    "Preferred Platform": "Telegram",
    "Core Value": "Luxury",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.81,
    "Digital Influence Score": 0.39,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  },
  {
    "Persona ID": "P-027",
    "Type": "High-Income Executive",
    "Age": 19,
    "Location": "Hyderabad",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Convenience",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.31,
    "Digital Influence Score": 0.63,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "Sustainability matters to me when making a purchase."
  },
  {
    "Persona ID": "P-028",
    "Type": "Middle-Class Parent",
    "Age": 50,
    "Location": "Bangalore",
    "Income Level": "Middle",
    "Preferred Platform": "Reddit",
    "Core Value": "Luxury",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Fashion",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.29,
    "Digital Influence Score": 0.68,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-029",
    "Type": "High-Income Executive",
    "Age": 57,
    "Location": "Ahmedabad",
    "Income Level": "Middle",
    "Preferred Platform": "Facebook",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.55,
    "Digital Influence Score": 0.95,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-030",
    "Type": "Blue-Collar Worker",
    "Age": 45,
    "Location": "Jaipur",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Luxury",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.94,
    "Digital Influence Score": 0.27,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-031",
    "Type": "Social Media Influencer",
    "Age": 55,
    "Location": "Lucknow",
    "Income Level": "Lower",
    "Preferred Platform": "Telegram",
    "Core Value": "Sustainability",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.97,
    "Digital Influence Score": 0.62,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-032",
    "Type": "Middle-Class Parent",
    "Age": 39,
    "Location": "Bangalore",
    "Income Level": "High",
    "Preferred Platform": "Telegram",
    "Core Value": "Convenience",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.84,
    "Digital Influence Score": 0.99,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-033",
    "Type": "Middle-Class Parent",
    "Age": 32,
    "Location": "Ahmedabad",
    "Income Level": "Middle",
    "Preferred Platform": "Twitter",
    "Core Value": "Sustainability",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.34,
    "Digital Influence Score": 0.22,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Sustainability matters to me when making a purchase."
  },
  {
    "Persona ID": "P-034",
    "Type": "Retired Individual",
    "Age": 23,
    "Location": "Jaipur",
    "Income Level": "High",
    "Preferred Platform": "Telegram",
    "Core Value": "Sustainability",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.92,
    "Digital Influence Score": 0.69,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-035",
    "Type": "Social Media Influencer",
    "Age": 60,
    "Location": "Chennai",
    "Income Level": "Lower",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Sustainability",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.16,
    "Digital Influence Score": 0.25,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-036",
    "Type": "Social Media Influencer",
    "Age": 55,
    "Location": "Hyderabad",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Twitter",
    "Core Value": "Sustainability",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.87,
    "Digital Influence Score": 0.77,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-037",
    "Type": "High-Income Executive",
    "Age": 47,
    "Location": "Lucknow",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Twitter",
    "Core Value": "Convenience",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.14,
    "Digital Influence Score": 0.78,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-038",
    "Type": "College Student",
    "Age": 42,
    "Location": "Kolkata",
    "Income Level": "Middle",
    "Preferred Platform": "YouTube",
    "Core Value": "Affordability",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Fashion",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.22,
    "Digital Influence Score": 0.55,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-039",
    "Type": "Small Business Owner",
    "Age": 61,
    "Location": "Bangalore",
    "Income Level": "Lower",
    "Preferred Platform": "Twitter",
    "Core Value": "Sustainability",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.52,
    "Digital Influence Score": 0.61,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "Brand loyalty plays a big role in my choices."
  },
  {
    "Persona ID": "P-040",
    "Type": "Social Media Influencer",
    "Age": 45,
    "Location": "Chennai",
    "Income Level": "High",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.48,
    "Digital Influence Score": 0.79,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "Sustainability matters to me when making a purchase."
  },
  {
    "Persona ID": "P-041",
    "Type": "Middle-Class Parent",
    "Age": 57,
    "Location": "Chennai",
    "Income Level": "Lower",
    "Preferred Platform": "YouTube",
    "Core Value": "Luxury",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.74,
    "Digital Influence Score": 0.72,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "Sustainability matters to me when making a purchase."
  },
  {
    "Persona ID": "P-042",
    "Type": "Middle-Class Parent",
    "Age": 19,
    "Location": "Jaipur",
    "Income Level": "Middle",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Luxury",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.28,
    "Digital Influence Score": 0.25,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  },
  {
    "Persona ID": "P-043",
    "Type": "Middle-Class Parent",
    "Age": 28,
    "Location": "Jaipur",
    "Income Level": "Lower",
    "Preferred Platform": "Instagram",
    "Core Value": "Convenience",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.53,
    "Digital Influence Score": 0.43,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  },
  {
    "Persona ID": "P-044",
    "Type": "Young Professional",
    "Age": 22,
    "Location": "Chennai",
    "Income Level": "Lower",
    "Preferred Platform": "Twitter",
    "Core Value": "Traditional Values",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.68,
    "Digital Influence Score": 0.35,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-045",
    "Type": "Freelancer",
    "Age": 36,
    "Location": "Lucknow",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Instagram",
    "Core Value": "Sustainability",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.22,
    "Digital Influence Score": 0.66,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-046",
    "Type": "Freelancer",
    "Age": 25,
    "Location": "Mumbai",
    "Income Level": "Lower",
    "Preferred Platform": "Facebook",
    "Core Value": "Sustainability",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Fashion",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.99,
    "Digital Influence Score": 0.75,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-047",
    "Type": "Small Business Owner",
    "Age": 31,
    "Location": "Jaipur",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "YouTube",
    "Core Value": "Affordability",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.27,
    "Digital Influence Score": 0.58,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "Brand loyalty plays a big role in my choices."
  },
  {
    "Persona ID": "P-048",
    "Type": "College Student",
    "Age": 61,
    "Location": "Mumbai",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Telegram",
    "Core Value": "Sustainability",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.84,
    "Digital Influence Score": 0.47,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I prefer word-of-mouth recommendations before buying."
  },
  {
    "Persona ID": "P-049",
    "Type": "Retired Individual",
    "Age": 46,
    "Location": "Hyderabad",
    "Income Level": "High",
    "Preferred Platform": "YouTube",
    "Core Value": "Traditional Values",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 1.0,
    "Digital Influence Score": 0.43,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-050",
    "Type": "Tech Enthusiast",
    "Age": 43,
    "Location": "Chennai",
    "Income Level": "High",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Traditional Values",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.76,
    "Digital Influence Score": 0.38,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "Sustainability matters to me when making a purchase."
  },
  {
    "Persona ID": "P-051",
    "Type": "High-Income Executive",
    "Age": 21,
    "Location": "Mumbai",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "YouTube",
    "Core Value": "Convenience",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.11,
    "Digital Influence Score": 0.52,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-052",
    "Type": "Social Media Influencer",
    "Age": 24,
    "Location": "Mumbai",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "YouTube",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.96,
    "Digital Influence Score": 0.9,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Brand loyalty plays a big role in my choices."
  },
  {
    "Persona ID": "P-053",
    "Type": "Retired Individual",
    "Age": 19,
    "Location": "Mumbai",
    "Income Level": "Lower",
    "Preferred Platform": "Facebook",
    "Core Value": "Traditional Values",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.54,
    "Digital Influence Score": 0.63,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-054",
    "Type": "Tech Enthusiast",
    "Age": 42,
    "Location": "Jaipur",
    "Income Level": "Middle",
    "Preferred Platform": "YouTube",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.72,
    "Digital Influence Score": 0.75,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  },
  {
    "Persona ID": "P-055",
    "Type": "Freelancer",
    "Age": 25,
    "Location": "Lucknow",
    "Income Level": "Middle",
    "Preferred Platform": "YouTube",
    "Core Value": "Luxury",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.96,
    "Digital Influence Score": 0.26,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-056",
    "Type": "Social Media Influencer",
    "Age": 29,
    "Location": "Chennai",
    "Income Level": "Middle",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Sustainability",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.1,
    "Digital Influence Score": 0.92,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  },
  {
    "Persona ID": "P-057",
    "Type": "Small Business Owner",
    "Age": 45,
    "Location": "Lucknow",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Telegram",
    "Core Value": "Luxury",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.14,
    "Digital Influence Score": 0.49,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I prefer word-of-mouth recommendations before buying."
  },
  {
    "Persona ID": "P-058",
    "Type": "Small Business Owner",
    "Age": 32,
    "Location": "Ahmedabad",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Twitter",
    "Core Value": "Convenience",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.42,
    "Digital Influence Score": 0.11,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Brand loyalty plays a big role in my choices."
  },
  {
    "Persona ID": "P-059",
    "Type": "Young Professional",
    "Age": 20,
    "Location": "Ahmedabad",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Luxury",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Fashion",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.3,
    "Digital Influence Score": 0.48,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-060",
    "Type": "Young Professional",
    "Age": 28,
    "Location": "Pune",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.14,
    "Digital Influence Score": 0.73,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Brand loyalty plays a big role in my choices."
  },
  {
    "Persona ID": "P-061",
    "Type": "Retired Individual",
    "Age": 60,
    "Location": "Delhi",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Reddit",
    "Core Value": "Luxury",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.24,
    "Digital Influence Score": 0.23,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I prefer word-of-mouth recommendations before buying."
  },
  {
    "Persona ID": "P-062",
    "Type": "Freelancer",
    "Age": 44,
    "Location": "Pune",
    "Income Level": "Middle",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.98,
    "Digital Influence Score": 0.23,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-063",
    "Type": "Social Media Influencer",
    "Age": 52,
    "Location": "Ahmedabad",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Facebook",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.99,
    "Digital Influence Score": 0.99,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-064",
    "Type": "Tech Enthusiast",
    "Age": 52,
    "Location": "Mumbai",
    "Income Level": "High",
    "Preferred Platform": "YouTube",
    "Core Value": "Luxury",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.13,
    "Digital Influence Score": 0.78,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  },
  {
    "Persona ID": "P-065",
    "Type": "College Student",
    "Age": 26,
    "Location": "Pune",
    "Income Level": "Lower",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.68,
    "Digital Influence Score": 0.95,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-066",
    "Type": "Middle-Class Parent",
    "Age": 52,
    "Location": "Mumbai",
    "Income Level": "Middle",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.25,
    "Digital Influence Score": 0.93,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Brand loyalty plays a big role in my choices."
  },
  {
    "Persona ID": "P-067",
    "Type": "Retired Individual",
    "Age": 42,
    "Location": "Kolkata",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.62,
    "Digital Influence Score": 0.66,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I prefer word-of-mouth recommendations before buying."
  },
  {
    "Persona ID": "P-068",
    "Type": "Blue-Collar Worker",
    "Age": 53,
    "Location": "Pune",
    "Income Level": "High",
    "Preferred Platform": "Facebook",
    "Core Value": "Sustainability",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.3,
    "Digital Influence Score": 0.58,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-069",
    "Type": "College Student",
    "Age": 59,
    "Location": "Hyderabad",
    "Income Level": "Middle",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Sustainability",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.15,
    "Digital Influence Score": 0.42,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Sustainability matters to me when making a purchase."
  },
  {
    "Persona ID": "P-070",
    "Type": "Social Media Influencer",
    "Age": 41,
    "Location": "Hyderabad",
    "Income Level": "High",
    "Preferred Platform": "Telegram",
    "Core Value": "Traditional Values",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.68,
    "Digital Influence Score": 0.91,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-071",
    "Type": "Retired Individual",
    "Age": 34,
    "Location": "Mumbai",
    "Income Level": "High",
    "Preferred Platform": "YouTube",
    "Core Value": "Affordability",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.79,
    "Digital Influence Score": 0.61,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  },
  {
    "Persona ID": "P-072",
    "Type": "Small Business Owner",
    "Age": 34,
    "Location": "Hyderabad",
    "Income Level": "Lower",
    "Preferred Platform": "Instagram",
    "Core Value": "Sustainability",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.39,
    "Digital Influence Score": 0.91,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Sustainability matters to me when making a purchase."
  },
  {
    "Persona ID": "P-073",
    "Type": "Young Professional",
    "Age": 58,
    "Location": "Lucknow",
    "Income Level": "Middle",
    "Preferred Platform": "Telegram",
    "Core Value": "Affordability",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Fashion",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.75,
    "Digital Influence Score": 0.31,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I prefer word-of-mouth recommendations before buying."
  },
  {
    "Persona ID": "P-074",
    "Type": "Retired Individual",
    "Age": 35,
    "Location": "Lucknow",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Reddit",
    "Core Value": "Traditional Values",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.57,
    "Digital Influence Score": 0.61,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "Brand loyalty plays a big role in my choices."
  },
  {
    "Persona ID": "P-075",
    "Type": "Freelancer",
    "Age": 21,
    "Location": "Ahmedabad",
    "Income Level": "High",
    "Preferred Platform": "Reddit",
    "Core Value": "Sustainability",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.83,
    "Digital Influence Score": 0.78,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "Brand loyalty plays a big role in my choices."
  },
  {
    "Persona ID": "P-076",
    "Type": "High-Income Executive",
    "Age": 51,
    "Location": "Mumbai",
    "Income Level": "Middle",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Traditional Values",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.15,
    "Digital Influence Score": 0.53,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "Brand loyalty plays a big role in my choices."
  },
  {
    "Persona ID": "P-077",
    "Type": "Retired Individual",
    "Age": 62,
    "Location": "Mumbai",
    "Income Level": "Lower",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Convenience",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.78,
    "Digital Influence Score": 0.8,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-078",
    "Type": "High-Income Executive",
    "Age": 58,
    "Location": "Pune",
    "Income Level": "Middle",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Convenience",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.95,
    "Digital Influence Score": 0.76,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-079",
    "Type": "Small Business Owner",
    "Age": 48,
    "Location": "Delhi",
    "Income Level": "High",
    "Preferred Platform": "Twitter",
    "Core Value": "Sustainability",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.19,
    "Digital Influence Score": 0.45,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-080",
    "Type": "Young Professional",
    "Age": 26,
    "Location": "Hyderabad",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Telegram",
    "Core Value": "Affordability",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.49,
    "Digital Influence Score": 0.15,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "Brand loyalty plays a big role in my choices."
  },
  {
    "Persona ID": "P-081",
    "Type": "Retired Individual",
    "Age": 53,
    "Location": "Mumbai",
    "Income Level": "High",
    "Preferred Platform": "Telegram",
    "Core Value": "Affordability",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.46,
    "Digital Influence Score": 0.19,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-082",
    "Type": "High-Income Executive",
    "Age": 53,
    "Location": "Hyderabad",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Telegram",
    "Core Value": "Affordability",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.28,
    "Digital Influence Score": 0.31,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-083",
    "Type": "Small Business Owner",
    "Age": 45,
    "Location": "Mumbai",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Facebook",
    "Core Value": "Affordability",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.32,
    "Digital Influence Score": 0.13,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I prefer word-of-mouth recommendations before buying."
  },
  {
    "Persona ID": "P-084",
    "Type": "Social Media Influencer",
    "Age": 44,
    "Location": "Mumbai",
    "Income Level": "Lower",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Traditional Values",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.46,
    "Digital Influence Score": 0.12,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-085",
    "Type": "High-Income Executive",
    "Age": 44,
    "Location": "Chennai",
    "Income Level": "High",
    "Preferred Platform": "YouTube",
    "Core Value": "Sustainability",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Fashion",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.3,
    "Digital Influence Score": 0.81,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I prefer word-of-mouth recommendations before buying."
  },
  {
    "Persona ID": "P-086",
    "Type": "Tech Enthusiast",
    "Age": 49,
    "Location": "Mumbai",
    "Income Level": "Lower",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Affordability",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.97,
    "Digital Influence Score": 0.65,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-087",
    "Type": "High-Income Executive",
    "Age": 57,
    "Location": "Delhi",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Sustainability",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Fashion",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.52,
    "Digital Influence Score": 0.22,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-088",
    "Type": "Freelancer",
    "Age": 26,
    "Location": "Pune",
    "Income Level": "High",
    "Preferred Platform": "Twitter",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.22,
    "Digital Influence Score": 0.34,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-089",
    "Type": "Tech Enthusiast",
    "Age": 50,
    "Location": "Pune",
    "Income Level": "Lower",
    "Preferred Platform": "YouTube",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.46,
    "Digital Influence Score": 0.44,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-090",
    "Type": "Young Professional",
    "Age": 64,
    "Location": "Hyderabad",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "YouTube",
    "Core Value": "Luxury",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.25,
    "Digital Influence Score": 0.19,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-091",
    "Type": "College Student",
    "Age": 47,
    "Location": "Pune",
    "Income Level": "High",
    "Preferred Platform": "YouTube",
    "Core Value": "Traditional Values",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.35,
    "Digital Influence Score": 0.42,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-092",
    "Type": "Middle-Class Parent",
    "Age": 32,
    "Location": "Pune",
    "Income Level": "Lower",
    "Preferred Platform": "Reddit",
    "Core Value": "Luxury",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.11,
    "Digital Influence Score": 0.65,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "Sustainability matters to me when making a purchase."
  },
  {
    "Persona ID": "P-093",
    "Type": "Small Business Owner",
    "Age": 31,
    "Location": "Kolkata",
    "Income Level": "High",
    "Preferred Platform": "Facebook",
    "Core Value": "Sustainability",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.56,
    "Digital Influence Score": 0.98,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-094",
    "Type": "High-Income Executive",
    "Age": 28,
    "Location": "Chennai",
    "Income Level": "Lower",
    "Preferred Platform": "Reddit",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.27,
    "Digital Influence Score": 0.97,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-095",
    "Type": "High-Income Executive",
    "Age": 51,
    "Location": "Ahmedabad",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Affordability",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.3,
    "Digital Influence Score": 0.4,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-096",
    "Type": "College Student",
    "Age": 50,
    "Location": "Jaipur",
    "Income Level": "Middle",
    "Preferred Platform": "YouTube",
    "Core Value": "Affordability",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Fashion",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.13,
    "Digital Influence Score": 0.96,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-097",
    "Type": "College Student",
    "Age": 56,
    "Location": "Pune",
    "Income Level": "High",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Luxury",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.4,
    "Digital Influence Score": 0.43,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "Brand loyalty plays a big role in my choices."
  },
  {
    "Persona ID": "P-098",
    "Type": "Blue-Collar Worker",
    "Age": 48,
    "Location": "Chennai",
    "Income Level": "Lower",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Convenience",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.56,
    "Digital Influence Score": 0.89,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Sustainability matters to me when making a purchase."
  },
  {
    "Persona ID": "P-099",
    "Type": "Social Media Influencer",
    "Age": 30,
    "Location": "Jaipur",
    "Income Level": "Middle",
    "Preferred Platform": "Facebook",
    "Core Value": "Luxury",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.99,
    "Digital Influence Score": 0.91,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-100",
    "Type": "Tech Enthusiast",
    "Age": 26,
    "Location": "Hyderabad",
    "Income Level": "Middle",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Affordability",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.11,
    "Digital Influence Score": 0.75,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  }
];