// File: src/app/mockData.js
// This file contains mock data for Indian consumer personas

export const MOCK_PERSONA_DATA = [
  {
    "Persona ID": "P-001",
    "Type": "High-Income Executive",
    "Age": 60,
    "Location": "Jaipur",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Instagram",
    "Core Value": "Sustainability",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.67,
    "Digital Influence Score": 0.55,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-002",
    "Type": "Young Professional",
    "Age": 46,
    "Location": "Chennai",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Twitter",
    "Core Value": "Convenience",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.85,
    "Digital Influence Score": 0.93,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-003",
    "Type": "High-Income Executive",
    "Age": 30,
    "Location": "Mumbai",
    "Income Level": "High",
    "Preferred Platform": "Reddit",
    "Core Value": "Luxury",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.41,
    "Digital Influence Score": 0.99,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  },
  {
    "Persona ID": "P-004",
    "Type": "Young Professional",
    "Age": 26,
    "Location": "Ahmedabad",
    "Income Level": "Middle",
    "Preferred Platform": "Reddit",
    "Core Value": "Sustainability",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.66,
    "Digital Influence Score": 0.11,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-005",
    "Type": "Blue-Collar Worker",
    "Age": 50,
    "Location": "Ahmedabad",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Facebook",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.59,
    "Digital Influence Score": 0.3,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-006",
    "Type": "High-Income Executive",
    "Age": 44,
    "Location": "Hyderabad",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Telegram",
    "Core Value": "Sustainability",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.18,
    "Digital Influence Score": 0.73,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I prefer word-of-mouth recommendations before buying."
  },
  {
    "Persona ID": "P-007",
    "Type": "Middle-Class Parent",
    "Age": 19,
    "Location": "Chennai",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Telegram",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.58,
    "Digital Influence Score": 0.44,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-008",
    "Type": "High-Income Executive",
    "Age": 40,
    "Location": "Jaipur",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.89,
    "Digital Influence Score": 0.9,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-009",
    "Type": "Middle-Class Parent",
    "Age": 59,
    "Location": "Ahmedabad",
    "Income Level": "High",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Entertainment",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.44,
    "Digital Influence Score": 0.95,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Positive",
    "AI-Simulated Thought Process": "Sustainability matters to me when making a purchase."
  },
  {
    "Persona ID": "P-010",
    "Type": "Social Media Influencer",
    "Age": 57,
    "Location": "Pune",
    "Income Level": "High",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Brand Loyalty",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.99,
    "Digital Influence Score": 0.6,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-011",
    "Type": "Middle-Class Parent",
    "Age": 24,
    "Location": "Mumbai",
    "Income Level": "Middle",
    "Preferred Platform": "Twitter",
    "Core Value": "Traditional Values",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 1.0,
    "Digital Influence Score": 0.72,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-012",
    "Type": "Middle-Class Parent",
    "Age": 18,
    "Location": "Delhi",
    "Income Level": "Lower",
    "Preferred Platform": "Reddit",
    "Core Value": "Traditional Values",
    "Personality Trait": "Minimalist",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.45,
    "Digital Influence Score": 0.84,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "Brand loyalty plays a big role in my choices."
  },
  {
    "Persona ID": "P-013",
    "Type": "Middle-Class Parent",
    "Age": 27,
    "Location": "Mumbai",
    "Income Level": "Middle",
    "Preferred Platform": "YouTube",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Community-Focused",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.22,
    "Digital Influence Score": 0.47,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I prefer word-of-mouth recommendations before buying."
  },
  {
    "Persona ID": "P-014",
    "Type": "College Student",
    "Age": 30,
    "Location": "Lucknow",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Traditional Values",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Daily Interaction",
    "Brand Sensitivity Score": 0.82,
    "Digital Influence Score": 0.69,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Sustainability matters to me when making a purchase."
  },
  {
    "Persona ID": "P-015",
    "Type": "Retired Individual",
    "Age": 55,
    "Location": "Chennai",
    "Income Level": "Middle",
    "Preferred Platform": "Twitter",
    "Core Value": "Sustainability",
    "Personality Trait": "Budget-Conscious",
    "Primary Purchase Method": "Hybrid (Both Online & Offline)",
    "Preferred Product Category": "Groceries",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.88,
    "Digital Influence Score": 0.75,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "Online reviews heavily influence my purchasing decisions."
  },
  {
    "Persona ID": "P-016",
    "Type": "Blue-Collar Worker",
    "Age": 19,
    "Location": "Kolkata",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "LinkedIn",
    "Core Value": "Luxury",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Electronics",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.61,
    "Digital Influence Score": 0.49,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I buy impulsively but regret later if the quality is bad."
  },
  {
    "Persona ID": "P-017",
    "Type": "Social Media Influencer",
    "Age": 48,
    "Location": "Bangalore",
    "Income Level": "Upper-Middle",
    "Preferred Platform": "Twitter",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Impulsive Buyer",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Health & Wellness",
    "Engagement Pattern": "Occasional Usage",
    "Brand Sensitivity Score": 0.42,
    "Digital Influence Score": 0.18,
    "Spending Behavior": "Frugal",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I'm always looking for the latest tech gadgets."
  },
  {
    "Persona ID": "P-018",
    "Type": "Social Media Influencer",
    "Age": 25,
    "Location": "Jaipur",
    "Income Level": "Middle",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Luxury",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Reviewer",
    "Brand Sensitivity Score": 0.93,
    "Digital Influence Score": 0.76,
    "Spending Behavior": "Luxury-Oriented",
    "General Sentiment on Products": "Neutral",
    "AI-Simulated Thought Process": "I prioritize affordability over brand reputation."
  },
  {
    "Persona ID": "P-019",
    "Type": "High-Income Executive",
    "Age": 21,
    "Location": "Ahmedabad",
    "Income Level": "Lower",
    "Preferred Platform": "Facebook",
    "Core Value": "Tech-Savvy",
    "Personality Trait": "Early Adopter",
    "Primary Purchase Method": "Online Shopping",
    "Preferred Product Category": "Home Appliances",
    "Engagement Pattern": "Lurker",
    "Brand Sensitivity Score": 0.97,
    "Digital Influence Score": 0.32,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  },
  {
    "Persona ID": "P-020",
    "Type": "High-Income Executive",
    "Age": 41,
    "Location": "Mumbai",
    "Income Level": "High",
    "Preferred Platform": "WhatsApp",
    "Core Value": "Traditional Values",
    "Personality Trait": "Research-Oriented",
    "Primary Purchase Method": "In-Store Shopping",
    "Preferred Product Category": "Fashion",
    "Engagement Pattern": "Active Sharer",
    "Brand Sensitivity Score": 0.11,
    "Digital Influence Score": 0.44,
    "Spending Behavior": "Moderate Spender",
    "General Sentiment on Products": "Negative",
    "AI-Simulated Thought Process": "I value discounts and cashback offers when shopping."
  }
];